import type { ComplianceResult, Violation, BatchResult } from "./types";
import { getFriendlyName } from "./rule-names";

const BRAND_NAVY = [36, 44, 101] as const;
const BRAND_PRIMARY = [79, 70, 229] as const;
const WHITE = [255, 255, 255] as const;
const LIGHT_GRAY = [248, 250, 252] as const;
const MID_GRAY = [148, 163, 184] as const;
const DARK = [15, 23, 42] as const;
const GREEN = [34, 197, 94] as const;
const RED = [239, 68, 68] as const;
const AMBER = [245, 158, 11] as const;
const CRITICAL_BG = [254, 242, 242] as const;
const HIGH_BG = [255, 251, 235] as const;
const MEDIUM_BG = [240, 253, 244] as const;

type RGB = readonly [number, number, number];

function verdictColor(verdict: string): RGB {
  switch (verdict.toUpperCase()) {
    case "PASS": return GREEN;
    case "FAIL": return RED;
    default: return AMBER;
  }
}

function severityColor(severity: string): RGB {
  switch (severity) {
    case "critical": return RED;
    case "high": return AMBER;
    default: return [34, 197, 94];
  }
}

function severityBg(severity: string): RGB {
  switch (severity) {
    case "critical": return CRITICAL_BG;
    case "high": return HIGH_BG;
    default: return MEDIUM_BG;
  }
}

function truncate(text: string, max: number): string {
  if (!text) return "";
  return text.length > max ? text.slice(0, max - 3) + "..." : text;
}

function wrapText(doc: any, text: string, x: number, maxWidth: number, lineHeight: number): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  lines.forEach((line: string) => {
    doc.text(line, x, doc.lastAutoTable?.finalY || 0);
  });
  return lines.length * lineHeight;
}

async function addCoverPage(doc: any, title: string, subtitle: string, meta: Record<string, string>) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  doc.setFillColor(...BRAND_NAVY);
  doc.rect(0, 0, w, h, "F");

  doc.setFillColor(...BRAND_PRIMARY);
  doc.rect(0, 0, w, 8, "F");
  doc.rect(0, h - 8, w, 8, "F");

  doc.setFillColor(255, 255, 255, 0.05);
  doc.circle(w * 0.85, h * 0.25, 80, "F");
  doc.circle(w * 0.15, h * 0.75, 60, "F");

  const logoY = 65;
  doc.setFillColor(...BRAND_PRIMARY);
  doc.roundedRect(w / 2 - 28, logoY - 20, 56, 56, 12, 12, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("BG", w / 2, logoY + 8, { align: "center" });

  doc.setTextColor(...WHITE);
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("BRANDGUARD", w / 2, logoY + 34, { align: "center" });
  doc.setFontSize(8);
  doc.setTextColor(180, 190, 220);
  doc.text("COMPLIANCE SUITE", w / 2, logoY + 43, { align: "center" });

  doc.setDrawColor(100, 116, 180);
  doc.setLineWidth(0.5);
  doc.line(w * 0.25, logoY + 56, w * 0.75, logoY + 56);

  doc.setTextColor(...WHITE);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(title, w * 0.7);
  let ty = logoY + 80;
  titleLines.forEach((line: string) => {
    doc.text(line, w / 2, ty, { align: "center" });
    ty += 12;
  });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 190, 220);
  doc.text(subtitle, w / 2, ty + 5, { align: "center" });

  let my = ty + 30;
  doc.setFontSize(9);
  Object.entries(meta).forEach(([key, value]) => {
    doc.setTextColor(140, 150, 180);
    doc.setFont("helvetica", "normal");
    doc.text(key, w / 2 - 50, my);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(value, w / 2 + 10, my);
    my += 8;
  });

  doc.setTextColor(120, 130, 160);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("This report is generated by BrandGuard AI Compliance Engine", w / 2, h - 25, { align: "center" });
  doc.text("Confidential — For internal use only", w / 2, h - 18, { align: "center" });
}

function addPageHeader(doc: any, pageTitle: string) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(...BRAND_NAVY);
  doc.rect(0, 0, w, 28, "F");
  doc.setFillColor(...BRAND_PRIMARY);
  doc.rect(0, 0, w, 4, "F");

  doc.setTextColor(...WHITE);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text("BRANDGUARD", 14, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6);
  doc.text("COMPLIANCE SUITE", 14, 20);

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(pageTitle, w - 14, 17, { align: "right" });
}

function addPageFooter(doc: any, pageNum: number) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setDrawColor(200, 210, 230);
  doc.setLineWidth(0.3);
  doc.line(14, h - 14, w - 14, h - 14);
  doc.setTextColor(...MID_GRAY);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("BrandGuard Compliance Report — Confidential", 14, h - 8);
  doc.text(`Page ${pageNum}`, w - 14, h - 8, { align: "right" });
}

function drawVerdictBadge(doc: any, x: number, y: number, verdict: string, confidence: number) {
  const vc = verdictColor(verdict);
  doc.setFillColor(...vc);
  doc.roundedRect(x, y, 80, 22, 4, 4, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  const label = verdict === "PASS" ? "Compliant" : verdict === "FAIL" ? "Non-Compliant" : "Needs Review";
  doc.text(label, x + 40, y + 10, { align: "center" });
  doc.setFontSize(8);
  doc.text(`${confidence}%`, x + 40, y + 18, { align: "center" });
}

function drawStatBox(doc: any, x: number, y: number, w: number, label: string, value: string, color: RGB) {
  doc.setFillColor(...LIGHT_GRAY);
  doc.roundedRect(x, y, w, 24, 3, 3, "F");
  doc.setTextColor(...color);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(value, x + w / 2, y + 12, { align: "center" });
  doc.setTextColor(...MID_GRAY);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text(label, x + w / 2, y + 20, { align: "center" });
}

function drawViolationsTable(doc: any, violations: Violation[], startY: number, pageTitle: string): number {
  let y = startY;
  const w = doc.internal.pageSize.getWidth();
  const maxW = w - 28;
  const pageH = doc.internal.pageSize.getHeight();

  if (violations.length === 0) {
    doc.setTextColor(...GREEN);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("No violations found", 14, y + 6);
    return y + 14;
  }

  violations.forEach((v, idx) => {
    const blockHeight = v.fix_suggestion ? 38 : 28;
    if (y + blockHeight > pageH - 20) {
      doc.addPage();
      addPageHeader(doc, pageTitle);
      addPageFooter(doc, doc.getNumberOfPages());
      y = 38;
    }

    const sc = severityColor(v.severity);
    const sbg = severityBg(v.severity);
    doc.setFillColor(...sbg);
    doc.roundedRect(14, y, maxW, blockHeight, 2, 2, "F");

    doc.setFillColor(...sc);
    doc.rect(14, y, 3, blockHeight, "F");

    doc.setTextColor(...sc);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const sevLabel = v.severity.charAt(0).toUpperCase() + v.severity.slice(1);
    doc.text(sevLabel, 20, y + 7);

    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(truncate(getFriendlyName(v.rule_id), 60), 50, y + 7);

    doc.setTextColor(71, 85, 105);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    const issueLines = doc.splitTextToSize(v.issue, maxW - 10);
    issueLines.slice(0, 2).forEach((line: string, li: number) => {
      doc.text(line, 20, y + 14 + li * 5);
    });

    if (v.fix_suggestion) {
      doc.setTextColor(34, 120, 80);
      doc.setFontSize(7);
      doc.setFont("helvetica", "italic");
      const fixLines = doc.splitTextToSize("Fix: " + v.fix_suggestion, maxW - 10);
      fixLines.slice(0, 2).forEach((line: string, li: number) => {
        doc.text(line, 20, y + 26 + li * 5);
      });
    }

    y += blockHeight + 3;
  });

  return y;
}

export async function generateSingleReportPDF(result: ComplianceResult, reportId?: string) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();

  const rid = reportId || result.session_id || "N/A";
  const now = new Date().toLocaleDateString("en-US", { weekday: "short", year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });

  await addCoverPage(doc, "Compliance Analysis Report", `Report ID: ${rid}`, {
    "Report ID:": rid,
    "Date:": now,
    "Content Type:": result.content_type_detected || "Unknown",
    "Verdict:": result.verdict,
    "Confidence:": `${result.confidence}%`,
    "Violations:": String(result.violations.length),
  });

  doc.addPage();
  const pageTitle = "Compliance Report";
  addPageHeader(doc, pageTitle);
  addPageFooter(doc, 2);

  let y = 40;

  drawVerdictBadge(doc, w / 2 - 40, y, result.verdict, result.confidence);
  y += 32;

  const passedCount = result.passed_details.filter(p => p.status !== "not_applicable").length;
  const naCount = result.passed_details.filter(p => p.status === "not_applicable").length;
  const boxW = (w - 28 - 16) / 5;
  drawStatBox(doc, 14, y, boxW, "Passed", String(passedCount), GREEN);
  drawStatBox(doc, 14 + boxW + 4, y, boxW, "Failed", String(result.violations.length), RED);
  drawStatBox(doc, 14 + (boxW + 4) * 2, y, boxW, "N/A", String(naCount), MID_GRAY);
  drawStatBox(doc, 14 + (boxW + 4) * 3, y, boxW, "Pass Rate", `${result.confidence}%`, BRAND_PRIMARY);
  drawStatBox(doc, 14 + (boxW + 4) * 4, y, boxW, "Verdict", result.verdict, verdictColor(result.verdict));
  y += 34;

  doc.setDrawColor(220, 230, 240);
  doc.setLineWidth(0.3);
  doc.line(14, y, w - 14, y);
  y += 6;

  doc.setFillColor(245, 247, 250);
  doc.roundedRect(14, y, w - 28, 8, 2, 2, "F");
  doc.setTextColor(...MID_GRAY);
  doc.setFontSize(6.5);
  doc.setFont("helvetica", "normal");
  const metaText = `Report ID: ${rid}  |  Content: ${result.content_type_detected || "N/A"}  |  Background: ${result.background_type_detected || "N/A"}  |  Dimensions: ${result.image_width || "?"}×${result.image_height || "?"}`;
  doc.text(metaText, w / 2, y + 5, { align: "center" });
  y += 14;

  if (result.summary) {
    doc.setTextColor(...DARK);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Summary", 14, y);
    y += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    const summaryLines = doc.splitTextToSize(result.summary, w - 28);
    summaryLines.forEach((line: string) => {
      if (y > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        addPageHeader(doc, pageTitle);
        addPageFooter(doc, doc.getNumberOfPages());
        y = 38;
      }
      doc.text(line, 14, y);
      y += 5;
    });
    y += 6;
  }

  if (result.violations.length > 0) {
    doc.setTextColor(...RED);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`Violations (${result.violations.length})`, 14, y);
    y += 8;
    y = drawViolationsTable(doc, result.violations, y, pageTitle);
    y += 6;
  }

  if (result.passed_details.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      addPageHeader(doc, pageTitle);
      addPageFooter(doc, doc.getNumberOfPages());
      y = 38;
    }
    doc.setTextColor(...GREEN);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`Passed Checks (${passedCount})`, 14, y);
    y += 7;

    const passedItems = result.passed_details.filter(p => p.status !== "not_applicable");
    passedItems.forEach((p) => {
      if (y > doc.internal.pageSize.getHeight() - 14) {
        doc.addPage();
        addPageHeader(doc, pageTitle);
        addPageFooter(doc, doc.getNumberOfPages());
        y = 38;
      }
      doc.setFillColor(240, 253, 244);
      doc.roundedRect(14, y - 3, w - 28, 8, 1, 1, "F");
      doc.setTextColor(...GREEN);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text("✓", 17, y + 2);
      doc.setTextColor(...DARK);
      doc.setFontSize(7.5);
      doc.text(truncate(getFriendlyName(p.rule_id), 80), 23, y + 2);
      y += 9;
    });
  }

  doc.save(`brandguard-report-${rid}.pdf`);
}

export async function generateBatchReportPDF(result: BatchResult) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();

  const now = new Date().toLocaleDateString("en-US", { weekday: "short", year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
  const bid = result.batch_id.slice(0, 8).toUpperCase();

  await addCoverPage(doc, "Batch Compliance Report", `${result.total_images} Images Analyzed`, {
    "Batch ID:": bid,
    "Date:": now,
    "Total Images:": String(result.total_images),
    "Passed:": String(result.summary.passed),
    "Failed:": String(result.summary.failed),
    "Warnings:": String(result.summary.warnings),
  });

  doc.addPage();
  const pageTitle = "Batch Report";
  addPageHeader(doc, pageTitle);
  addPageFooter(doc, 2);

  let y = 40;

  doc.setTextColor(...DARK);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Batch Summary", 14, y);
  y += 12;

  const boxW = (w - 28 - 12) / 4;
  drawStatBox(doc, 14, y, boxW, "Total", String(result.total_images), BRAND_PRIMARY);
  drawStatBox(doc, 14 + boxW + 4, y, boxW, "Passed", String(result.summary.passed), GREEN);
  drawStatBox(doc, 14 + (boxW + 4) * 2, y, boxW, "Failed", String(result.summary.failed), RED);
  drawStatBox(doc, 14 + (boxW + 4) * 3, y, boxW, "Warnings", String(result.summary.warnings), AMBER);
  y += 34;

  doc.setDrawColor(220, 230, 240);
  doc.setLineWidth(0.3);
  doc.line(14, y, w - 14, y);
  y += 8;

  result.results.forEach((r, idx) => {
    const violationBlockH = r.violations.length > 0 ? Math.min(r.violations.length * 20, 80) + 16 : 8;
    const neededH = 36 + violationBlockH;

    if (y + neededH > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      addPageHeader(doc, pageTitle);
      addPageFooter(doc, doc.getNumberOfPages());
      y = 38;
    }

    const vc = verdictColor(r.verdict);
    doc.setFillColor(...LIGHT_GRAY);
    doc.roundedRect(14, y, w - 28, 28, 3, 3, "F");
    doc.setFillColor(...vc);
    doc.rect(14, y, 4, 28, "F");

    doc.setTextColor(...DARK);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`${idx + 1}. ${truncate(r.image_name, 50)}`, 22, y + 10);

    doc.setFillColor(...vc);
    doc.roundedRect(w - 70, y + 3, 52, 10, 2, 2, "F");
    doc.setTextColor(...WHITE);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    const vLabel = r.verdict === "PASS" ? "PASS" : r.verdict === "FAIL" ? "FAIL" : "WARNING";
    doc.text(`${vLabel} — ${r.confidence}%`, w - 44, y + 9, { align: "center" });

    doc.setTextColor(...MID_GRAY);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(`${r.violations.length} violation${r.violations.length !== 1 ? "s" : ""}  |  ${r.passed_details.filter(p => p.status !== "not_applicable").length} passed  |  ${r.passed_details.filter(p => p.status === "not_applicable").length} N/A`, 22, y + 20);

    y += 32;

    if (r.violations.length > 0) {
      r.violations.forEach((v) => {
        if (y + 18 > doc.internal.pageSize.getHeight() - 20) {
          doc.addPage();
          addPageHeader(doc, pageTitle);
          addPageFooter(doc, doc.getNumberOfPages());
          y = 38;
        }
        const sc = severityColor(v.severity);
        const sbg = severityBg(v.severity);
        doc.setFillColor(...sbg);
        doc.roundedRect(22, y, w - 40, 14, 2, 2, "F");
        doc.setFillColor(...sc);
        doc.rect(22, y, 2, 14, "F");

        doc.setTextColor(...sc);
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "bold");
        doc.text(v.severity.toUpperCase(), 27, y + 5);

        doc.setTextColor(...DARK);
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "bold");
        doc.text(truncate(getFriendlyName(v.rule_id), 50), 48, y + 5);

        doc.setTextColor(71, 85, 105);
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "normal");
        doc.text(truncate(v.issue, 90), 27, y + 11);

        y += 17;
      });
    }

    if (r.summary) {
      if (y + 18 > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        addPageHeader(doc, pageTitle);
        addPageFooter(doc, doc.getNumberOfPages());
        y = 38;
      }
      doc.setTextColor(71, 85, 105);
      doc.setFontSize(7);
      doc.setFont("helvetica", "italic");
      const sLines = doc.splitTextToSize(r.summary, w - 48);
      sLines.slice(0, 3).forEach((line: string) => {
        doc.text(line, 22, y);
        y += 4.5;
      });
    }

    y += 8;
  });

  doc.save(`brandguard-batch-${bid}.pdf`);
}
