const friendlyRuleName: Record<string, string> = {
  "REG-01": "Nicotine Warning Banner",
  "REG-02": "18+ Age Restriction Icon",
  "REG-03": "Risk Communication Text",
  "REG-04": "Regulatory Placement (Top/Bottom)",
  "REG-05": "Bilingual Warning (EN + FR)",
  "LOGO-01": "Logo Appearance & Halo",
  "LOGO-02": "Logo on Gradient Background",
  "LOGO-03": "Logo Colour on Gradient",
  "LOGO-04": "Colour vs Monochrome Logo",
  "LOGO-05": "C Halo Gradient Required",
  "LOGO-06": "Logo Text Colour on White",
  "LOGO-07": "Logo on Light Image",
  "LOGO-08": "Logo Colour on Light Image",
  "LOGO-09": "Logo on Dark Image",
  "LOGO-10": "Logo Colour on Dark Image",
  "LOGO-11": "Logo Clear Space Zone",
  "LOGO-12": "Minimum Logo Size",
  "LOGO-13": "Original Logo Design",
  "LOGO-14": "NRT Lockup Text",
  "LOGO-15": "NRT Lockup Typeface",
  "LOGO-DONT-01": "C Halo Present",
  "LOGO-DONT-02": "Halo Only on C Letter",
  "LOGO-DONT-03": "No Outline Over Halo",
  "LOGO-DONT-04": "Halo Size Proportional",
  "LOGO-DONT-05": "No Gradient in Logo Text",
  "LOGO-DONT-06": "Halo Visibility",
  "LOGO-DONT-07": "No Outlined Logo Text",
  "LOGO-DONT-08": "No Reversed Halo Outline",
  "LOGO-DONT-09": "Halo Colour Contrast",
  "LOGO-DONT-10": "Logo on Dark Background",
  "LOGO-DONT-11": "No Halo on Other Letters",
  "LOGO-DONT-12": "Logo Colour Not Reversed",
  "LOGO-DONT-13": "Logo Layout Integrity",
  "LOGO-DONT-14": "Halo Matches Palette",
  "LOGO-DONT-15": "Halo Shape (Circular)",
  "LOGOBG-DONT-01": "Halo vs Background Colour",
  "LOGOBG-DONT-02": "Halo Visibility on Background",
  "LOGOBG-DONT-03": "Logo & Gradient Match",
  "LOGOBG-DONT-04": "Secondary Halo Not White",
  "LOGOBG-DONT-05": "No Gradient in Text on Gradient",
  "LOGOBG-DONT-06": "Navy Logo Not on Dark",
  "LOGOBG-DONT-07": "White Logo Not on Light",
  "LOGOBG-DONT-08": "No Logo in Shapes",
  "GRAD-01": "Gradient Direction",
  "GRAD-02": "Gradient Colour Pairing",
  "GRAD-03": "Gradient Contrast",
  "GRAD-04": "Grey Gradient Usage",
  "GRAD-05": "Gradient Consistency",
  "COLOR-01": "Primary Colour Usage",
  "COLOR-02": "Secondary Colour as Accent",
  "COLOR-03": "Flavour Colour Palette",
  "COLOR-04": "Secondary Not as Background",
  "CONTENT-01": "Flavour Content Rules",
  "CONTENT-02": "Educational Content Rules",
  "CONTENT-03": "Brand Purpose Content",
  "CONTENT-DONT-01": "No Secondary Colour Background",
  "CONTENT-DONT-02": "No Gradient for Non-Flavour",
  "CONTENT-DONT-03": "Grey Gradient Restriction",
  "CONTENT-DONT-04": "Product on White Background",
  "TYPO-01": "Santral Typeface",
  "TYPO-02": "Typeface Consistency",
  "TYPO-03": "NRT Lockup Typography",
};

export function getFriendlyName(ruleId: string): string {
  return friendlyRuleName[ruleId] || ruleId.replace(/-/g, " ");
}
